version: '3.8'

services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3088:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development